import express from "express";
import jwt from "jsonwebtoken";
import { getSecret } from "../init/initializeSecrets.js";

const router = express.Router();

/**
 * Refreshes tokens. Also sends the right HTTP codes in response
 * @param res - `Response` object generated by Express
 * @param password - Password given by a user to be checked
 */
function generateNewTokens(res: express.Response, password: string) {
  if (password === process.env.PIXIE_PASSWORD) {
    const refreshToken = jwt.sign({ id: crypto.randomUUID() }, getSecret(), {
      expiresIn: "15m",
    });

    jwt.sign({ password }, getSecret(), { expiresIn: "7d" }, (err, token) => {
      if (token) {
        res.cookie("authentication", token, {
          maxAge: 1e3 * 60 * 60 * 24 * 7, // 7 days
          httpOnly: true,
          signed: true,
          sameSite: "lax",
        });

        res.status(200).send(refreshToken);
      } else {
        res.sendStatus(500);
      }
    });

    return;
  }

  res.sendStatus(401);
}

router.post("/", (req, res) => {
  const { password }: { password: string } = req.body;

  generateNewTokens(res, password);
});

router.post("/refresh", (req, res) => {
  const authCookie = req.signedCookies.authentication;

  if (typeof authCookie !== "string") {
    res.sendStatus(401);
    return;
  }

  jwt.verify(authCookie, getSecret(), (error, decoded) => {
    if (
      decoded &&
      typeof decoded !== "string" &&
      typeof decoded.password === "string"
    ) {
      // This also refreshes the "session" token (authCookie). However, it doesn't invalidate the old authCookie
      generateNewTokens(res, decoded.password);
    } else {
      res.sendStatus(401);
    }
  });
});

export default router;
